### ISSUE TITLE
ch2.4.3

### ISSUE THREAD

**Issue by chulphan** [han41858/Angular-Development-with-TypeScript#47]
5.angular seed 실행하는 중에 콘솔에서 이러한 에러를 내뿜습니다.

Unhandled Promise rejection: (SystemJS) Cannot read property 'base64encode' of undefined
	TypeError: Cannot read property 'base64encode' of undefined
	    at Object.base64encode (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:12079:18)
	    at Object.getSourceMappingURL (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:73929:46)
	    at printSourceFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74550:48)
	    at emitJsFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74499:13)
	    at emitSourceFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74456:13)
	    at forEachEmittedFile (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74365:30)
	    at Object.emitFiles (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74446:9)
	    at emitWorker (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:78992:33)
	    at http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:78952:66
	    at runWithCancellationToken (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:79043:24)
	Error loading http://192.168.127.1:8080/app/main.ts ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) Cannot read property 'base64encode' of undefined
	TypeError: Cannot read property 'base64encode' of undefined
	    at Object.base64encode (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:12079:18)
	    at Object.getSourceMappingURL (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:73929:46)
	    at printSourceFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74550:48)
	    at emitJsFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74499:13)
	    at emitSourceFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74456:13)
	    at forEachEmittedFile (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74365:30)
	    at Object.emitFiles (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74446:9)
	    at emitWorker (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:78992:33)
	    at http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:78952:66
	    at runWithCancellationToken (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:79043:24)
	Error loading http://192.168.127.1:8080/app/main.ts
	    at Object.base64encode (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:12079:18)
	    at Object.getSourceMappingURL (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:73929:46)
	    at printSourceFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74550:48)
	    at emitJsFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74499:13)
	    at emitSourceFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74456:13)
	    at forEachEmittedFile (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74365:30)
	    at Object.emitFiles (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74446:9)
	    at emitWorker (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:78992:33)
	    at http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:78952:66
	    at runWithCancellationToken (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:79043:24)
	Error loading http://192.168.127.1:8080/app/main.ts (SystemJS) Cannot read property 'base64encode' of undefined
	TypeError: Cannot read property 'base64encode' of undefined
	    at Object.base64encode (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:12079:18)
	    at Object.getSourceMappingURL (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:73929:46)
	    at printSourceFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74550:48)
	    at emitJsFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74499:13)
	    at emitSourceFileOrBundle (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74456:13)
	    at forEachEmittedFile (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74365:30)
	    at Object.emitFiles (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:74446:9)
	    at emitWorker (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:78992:33)
	    at http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:78952:66
	    at runWithCancellationToken (http://192.168.127.1:8080/node_modules/typescript/lib/typescript.js:79043:24)
	Error loading http://192.168.127.1:8080/app/main.ts
api.onUnhandledError @ zone.js:665
handleUnhandledRejection @ zone.js:692
_loop_1 @ zone.js:682
api.microtaskDrainDone @ zone.js:686
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2969
ZoneDelegate.scheduleTask @ zone.js:407
Zone.scheduleTask @ zone.js:232
Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:3001
proto.(anonymous function) @ zone.js:1394
fetchTextFromURL @ system.src.js:1043
(anonymous) @ system.src.js:1779
ZoneAwarePromise @ zone.js:891
(anonymous) @ system.src.js:1778
(anonymous) @ system.src.js:2803
(anonymous) @ system.src.js:3381
(anonymous) @ system.src.js:3713
(anonymous) @ system.src.js:4105
(anonymous) @ system.src.js:4570
(anonymous) @ system.src.js:4839
(anonymous) @ system.src.js:408
ZoneDelegate.invoke @ zone.js:388
Zone.run @ zone.js:138
(anonymous) @ zone.js:872
ZoneDelegate.invokeTask @ zone.js:421
Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
ZoneDelegate.scheduleTask @ zone.js:410
Zone.scheduleTask @ zone.js:232
Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
(anonymous) @ system.src.js:4797
import @ system.src.js:830
(anonymous) @ system.src.js:1802
(anonymous) @ (index):13

구글링을 해도 어떻게 해야되는지 전혀 모르겠어요...

package.json

{
  "name": "angular-seed",
  "descripton" : "An initial yarn-managed project for ch2",
  "private" : true,

  "scripts" : {
    "start" : "live-server"
  },

  "dependencies" : {
    "@angular/common" : "^4.1.0",
    "@angular/compiler" : "^4.1.0",
    "@angular/core" : "^4.1.0",
    "@angular/forms" : "^4.1.0",
    "@angular/http" : "^4.1.0",
    "@angular/platform-browser" : "^4.1.0",
    "@angular/platform-browser-dynamic" : "^4.1.0",
    "@angular/router" : "^4.1.0",
    "core-js" : "^2.4.1",
    "rxjs" : "5.3.0",
    "systemjs" : "0.19.47",
    "zone.js" : "^0.8.12"
  },

  "devDependencies" : {
    "live-server" : "^1.2.0",
    "typescript" : "^2.3.3"
  }

}

index.html

<!DOCTYPE html>
<html>
  <head>
    <title>Angular seed project</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="node_modules/typescript/lib/typescript.js"></script>
    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="./systemjs.config.js"></script>
    <script>
      System.import('app').catch(function(err) {
        console.log(err);
      });
    </script>
  </head>
  <body>
    <app>Loading...</app>
  </body>
</html>

해결책 좀 부탁드립니다.. 좋은 주말되세요!! 

감사합니다.

**Comment by chulphan** [comment]
typescript 버전이 문제였습니다. 
devDependencies 부분에서 ^2.3.3 이 아니라 2.3.3 으로 수정해주니 괜찮아졌네요

+) 그런데 저만 이런 문제를 겪었다는게 신기하네요...

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

제 블로그에 이 내용으로 문의하신 분이 있었습니다.
해결방법은 같았던 것 같네요 ㅎ

[TypeScript 이슈 링크](https://github.com/Microsoft/TypeScript/issues/24638) 참고하세요.

감사합니다.
