### ISSUE TITLE
2.5 실습 에러

### ISSUE THREAD

**Issue by chulphan** [han41858/Angular-Development-with-TypeScript#48]
아래와 같은 에러가 발생합니다.

?productPrice=:15 Error: (SystemJS) Can't resolve all parameters for ApplicationComponent: (?).
	Error: Can't resolve all parameters for ApplicationComponent: (?).
	    at syntaxError (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:6:2689)
	    at CompileMetadataResolver._getDependenciesMetadata (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:23449)
	    at CompileMetadataResolver._getTypeMetadata (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:20387)
	    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:8470)
	    at CompileMetadataResolver._getEntryComponentMetadata (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:26775)
	    at eval (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:16043)
	    at Array.map (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:16011)
	    at JitCompiler._loadModules (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:170:8011)
	    at JitCompiler._compileModuleAndComponents (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:170:7400)
	Error loading http://127.0.0.1:8080/app/main.ts
	    at syntaxError (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:6:2689)
	    at CompileMetadataResolver._getDependenciesMetadata (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:23449)
	    at CompileMetadataResolver._getTypeMetadata (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:20387)
	    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:8470)
	    at CompileMetadataResolver._getEntryComponentMetadata (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:26775)
	    at eval (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:16043)
	    at Array.map (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:144:16011)
	    at JitCompiler._loadModules (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:170:8011)
	    at JitCompiler._compileModuleAndComponents (http://127.0.0.1:8080/node_modules/@angular/compiler/bundles/compiler.umd.min.js:170:7400)
	Error loading http://127.0.0.1:8080/app/main.ts

application.component.ts 에 있는 ApplicationComponent 클래스에 있는 내용을 모두 주석 처리하고 실행해보니 에러는 없이 동작됩니다.

위의 에러를 어떻게 해결해야할지 모르겠습니다.

다 작성한 코드를 저자님의 깃헙에 있는 코드와 책에 있는 코드랑 비교해봐도 다른 부분도 없는데...

정말 난감하네요.

꼭 답변 부탁드립니다.

감사합니다.

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

이 에러는 의존성 주입에 실패했을때 날 수 있는 에러인데...
코드를 어떻게 작성하셨는지 모르니 답변을 드리기가 어렵네요... ㅎ 

해결되었나요?

**Comment by chulphan** [comment]
systemjs.config.js 에 typescriptOptions 를 typescriptOption 으로 써서 발생한 오류입니다.. 귀찮게 해드려서 죄송합니다 그리고 답변해주셔서 감사드립니다
